version: "3.8"

networks:
  core:
    ipam:
      driver: default
      config:
        - subnet: 10.80.95.0/24
  rf:
    ipam:
      driver: default
      config:
        - subnet: 10.80.97.0/24

services:
  srsepc:
    container_name: srsepc
    image: srsran
    networks:
      core:
        ipv4_address: 10.80.95.10
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
    volumes:
      - ./config:/etc/srsran:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - srsepc
      - --mme.mme_bind_addr=10.80.95.10
      - --spgw.gtpu_bind_addr=10.80.95.10
  
  srsenb:
    container_name: srsenb
    image: srsran
    networks:
      core:
        ipv4_address: 10.80.95.11
      rf:
        ipv4_address: 10.80.97.11
    cap_add:
      - SYS_NICE
    volumes:
      - ./config:/etc/srsran:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - srsenb
      - --rf.device_name=zmq
      - --rf.device_args="id=enb,fail_on_disconnect=true,tx_port=tcp://*:2000,rx_port=tcp://10.80.97.12:2001,base_srate=23.04e6"
      - --enb.mme_addr=10.80.95.10
      - --enb.gtp_bind_addr=10.80.95.11
      - --enb.s1c_bind_addr=10.80.95.11
      - --enb_files.sib_config=/etc/srsran/sib.conf
  
  srsue:
    container_name: srsue
    image: srsran
    networks:
      rf:
        ipv4_address: 10.80.97.12
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
    volumes:
      - ./config:/etc/srsran:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - srsenb
    command:
      - srsue 
      - --rf.device_name=zmq
      - --rf.device_args="id=ue,fail_on_disconnect=true,tx_port=tcp://*:2001,rx_port=tcp://10.80.97.11:2000,base_srate=23.04e6"
  
  # srsue2:
  #   <<: *ue-settings
  #   container_name: virtual-srsue2
  #   command: "srsue ue.conf.fauxrf --usim.imsi=001010123456780"
