version: "2.2"

x-srsue: &ue-settings
  image: srslte
  ipc: "container:virtual-srsenb"
  cap_add:
    - NET_ADMIN
    - SYS_NICE
  devices:
    - /dev/net/tun
  depends_on:
    - srsenb
  command: "srsue ue.conf.fauxrf"

networks:
  corenet:
    ipam:
      driver: default
      config:
        - subnet: 10.80.95.0/24

services:
  srsepc:
    container_name: virtual-srsepc
    image: srsran
    networks:
      corenet:
        ipv4_address: 10.80.95.10
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
    command:
      - srsepc
      - epc.conf
      - --mme.mme_bind_addr=10.80.95.10
      - --spgw.gtpu_bind_addr=10.80.95.10
  
  srsenb:
    container_name: virtual-srsenb
    image: srsran
    networks:
      corenet:
        ipv4_address: 10.80.95.11
    ipc: shareable
    cap_add:
      - SYS_NICE
    command:
      - srsenb
      - enb.conf.fauxrf
      - --enb.mme_addr=10.80.95.10
      - --enb.gtp_bind_addr=10.80.95.11
      - --enb.s1c_bind_addr=10.80.95.11
      - --enb_files.sib_config=sib.conf
  
  srsue:
    <<: *ue-settings
    container_name: virtual-srsue
  
  # srsue2:
  #   <<: *ue-settings
  #   container_name: virtual-srsue2
  #   command: "srsue ue.conf.fauxrf --usim.imsi=001010123456780"
