version: "3.8"

networks:
  core:
    ipam:
      driver: default
      config:
        - subnet: 10.80.95.0/24
  rf:
    ipam:
      driver: default
      config:
        - subnet: 10.80.97.0/24

services:
  srsepc:
    container_name: srsepc
    image: srsran
    build: .
    networks:
      core:
        ipv4_address: 10.80.95.10
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
    volumes:
      - ../config:/etc/srsran:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - srsepc
      - --mme.mme_bind_addr=10.80.95.10
      - --spgw.gtpu_bind_addr=10.80.95.10
  
  srsenb:
    container_name: srsenb
    image: srsran
    build: .
    networks:
      core:
        ipv4_address: 10.80.95.11
      rf:
        ipv4_address: 10.80.97.11
    cap_add:
      - SYS_NICE
    volumes:
      - ../config:/etc/srsran:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - srsenb
      - --enb.mme_addr=10.80.95.10
      - --enb.gtp_bind_addr=10.80.95.11
      - --enb.s1c_bind_addr=10.80.95.11
      - --rf.device_name=zmq
      - --rf.device_args="id=enb,fail_on_disconnect=true,tx_port0=tcp://*:2000,rx_port0=tcp://10.80.97.12:2001,tx_port1=tcp://*:2100,rx_port1=tcp://10.80.97.12:2101,base_srate=23.04e6"
      - --enb_files.sib_config=/etc/srsran/sib.conf
      - --enb_files.rr_config=/etc/srsran/rr.5g.conf
  
  srsue:
    container_name: srsue
    image: srsran
    build: .
    networks:
      rf:
        ipv4_address: 10.80.97.12
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
    volumes:
      - ../config:/etc/srsran:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - srsenb
    command:
      - srsue 
      - --rf.device_name=zmq
      - --rf.device_args="id=ue,fail_on_disconnect=true,tx_port0=tcp://*:2001,rx_port0=tcp://10.80.97.11:2000,tx_port1=tcp://*:2101,rx_port1=tcp://10.80.97.11:2100,base_srate=23.04e6"
      - --rat.nr.bands=3,78
      - --rat.nr.nof_carriers=1
      - --rrc.release=15
