name: Deploy marp slides to Github Pages

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Move files around
      run: mv slides docs

    - name: Cache docker containers
      uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Build & Deploy to GitHub Pages
      env:
        MARP_ARGS: "docs/SLIDES.md -o docs/index.html --html"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PUBLISH_TO_BRANCH: gh-pages
      uses: ralexander-phi/marp-action@master